#!/usr/bin/env python3.3

import sys
import io
from entry__ import main

if __name__ == "__main__" :
    argc = len(sys.argv)
    usage = "Usage: " + sys.argv[0] + "file.kh | file.kc [file.kh | file.kc]\n"
    print_debug = False
    if argc < 2:
        sys.stderr.write(usage)
        sys.exit(1)
    i = 1
    while argc > 1 :
        if sys.argv[i] == "--print_debug":
            print_debug = True	
        else:
            current = sys.argv[i].rsplit(".", 1)
            if len(current) != 2 :
                sys.stderr.write(current[0] + " has no extension\n");
                sys.stderr.write(usage)
                sys.exit(1)
            if current[1] != "kh" and current[1] != "kc" :
                sys.stderr.write("Extension ." + current[1] + " invalid\n");
                sys.stderr.write(usage)
                sys.exit(1)
            res = str(main.entry(sys.argv[i], print_debug, current))
            if res:
                f = open(current[0] + "." + current[1][1:], 'w')
                f.write(res)
                f.close()
        i = i + 1
        argc = argc - 1
    sys.exit(0)
        
